/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as IndexRouteImport } from './routes/index'

const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/modules': typeof ModulesRoute
  '/prediction': typeof PredictionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/modules': typeof ModulesRoute
  '/prediction': typeof PredictionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparison': typeof ComparisonRoute
  '/modules': typeof ModulesRoute
  '/prediction': typeof PredictionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparison' | '/modules' | '/prediction'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparison' | '/modules' | '/prediction'
  id: '__root__' | '/' | '/comparison' | '/modules' | '/prediction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparisonRoute: typeof ComparisonRoute
  ModulesRoute: typeof ModulesRoute
  PredictionRoute: typeof PredictionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparisonRoute: ComparisonRoute,
  ModulesRoute: ModulesRoute,
  PredictionRoute: PredictionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
